---
title: "Bias in 311 Response"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This repo contains the code and data for reproducing *Bias in 311 Response*.

> **Abstract:** This paper explores the interaction between citizen satisfaction in local government with 311 service usage, and related bias in who may be using these services more. I combine open-access data on 311 service usage and property violations from KCMO OpenData with Census data, and a proprietary citizen satisfaction survey conducted by the Kansas City Office of Performance Management. I find that certain demographics like gender, race, and income affect likelihood of contacting city services, but the strongest predictors of 311 usage are pre-existing and regular interactions with city services — like recycling, visiting parks, and visiting the city website.
>
> **Keywords:** 311 Complaint, City governance, Classification, Bias

Click on the “fork” button at the very top right of the page to create
an independent copy of the repo within your own GitHub account.
Alternately, click on the green “clone or download” button just below
that to download the repo to your local computer.

## Software

The analysis for this project was conducted in *R*. 

## Problems

I cannot upload the citizen satisfaction survey data per my agreement with the Kansas City Office of Performance Management. All other code should run. Please contact me if you wish to run my code.

If you have any trouble running the code, or find any errors, please
file an issue and I’ll look into it.

## License

The software code contained within this repository is made available
under the [Unlicense](https://unlicense.org).

